### ISSUE TITLE
[BUG] Error validating scan types: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by azizabah** [Checkmarx/ast-azure-plugin#454] opened 2023-11-30 15:31 UTC
### Describe the bug
The Checkmarx AST@2 task is throwing an error:

`Creating directory
Error validating scan types: invalid character '<' looking for beginning of value
Exit code received from AST-CLI: 1`

### Expected behavior
It doesn't throw an error.

### Actual behavior
It throws an error. 

### Environment
- [AZURE PLUGIN version](task: Checkmarx AST@2)
- Platform - Image: ubuntu-latest

### Logs
2023-11-30T15:23:27.2264094Z ##[section]Starting: CheckmarxAST
2023-11-30T15:23:27.2268612Z ==============================================================================
2023-11-30T15:23:27.2268739Z Task         : Checkmarx AST
2023-11-30T15:23:27.2268798Z Description  : Add Secure Source Code Analysis inside your build process
2023-11-30T15:23:27.2268904Z Version      : 2.0.28
2023-11-30T15:23:27.2268960Z Author       : Checkmarx
2023-11-30T15:23:27.2269016Z Help         : https://github.com/CheckmarxDev/checkmarx-ast-azure-plugin#readme
2023-11-30T15:23:27.2269479Z ==============================================================================
2023-11-30T15:23:29.3322131Z No client ID and secret configured
2023-11-30T15:23:29.3334629Z Project name: some-service
2023-11-30T15:23:29.3336232Z Branch name: $(System.PullRequest.SourceBranch)
2023-11-30T15:23:29.3337420Z Agent: Azure DevOps
2023-11-30T15:23:29.3339095Z Additional Params: 
2023-11-30T15:23:29.3458589Z Creating directory
2023-11-30T15:23:29.4682336Z Error validating scan types: invalid character '<' looking for beginning of value
2023-11-30T15:23:29.4726029Z Exit code received from AST-CLI: 1
2023-11-30T15:23:29.4808641Z ##[section]Finishing: CheckmarxAST

**Comment by OrShamirCM** [comment] 2024-06-16 10:09
The issue can’t be reproduced. It happened when we had an error in one of our core servers. It's not a common issue and not related to the CLI (only the error message is).
I am closing as I can't reproduce.

**Closed by OrShamirCM** 2024-06-16 10:09 UTC
Labels: bug
